#!/usr/bin/env python2.7
# connect and serve a query to the firstbits db


import mysql.connector

cnx = mysql.connector.connect(user='root', 
                              password='mysqlroot', 
                              host='localhost',
                              database='firstbits3')
cursor = cnx.cursor()

def ad2fb(cursor,ad):
  cursor.execute("SELECT * FROM main WHERE address='%s';" % ad)
  reply = cursor.fetchone()
  if reply:
    print("address: {0}\nfirstbits: {1}\nheight: {2}".format(reply[1], reply[2], reply[3]))

def fb2ad(cursor,fb):
  cursor.execute("SELECT * FROM main WHERE firstbits='%s';" % fb)
  reply = cursor.fetchone()
  if reply:
    print("address: {0}\nfirstbits: {1}\nheight: {2}".format(reply[1], reply[2], reply[3]))

import sys
if sys.argv[1] == '-fb':
  fb2ad(cursor, sys.argv[2])
elif sys.argv[1] == '-ad':
  ad2fb(cursor, sys.argv[2])
else:
  print("error, give an fb or an ad with -fb FB or -ad AD")

cursor.close()
cnx.close()
